config/routes.rb
Rails.application.routes.draw do
  root 'checklists#index'
  
  resources :checklists do
    resources :questions, only: [:create]
  end

  resources :checklists do
    resources :audits, except: [:index, :create] do
        resources :answers, only: [:create, :edit]
    end
  end
  
  resources :audits, only: [:index]
  devise_for :users
  
  # If no route matches
  # match ":url" => "application#redirect_user", :constraints => { :url => /.*/ }
  # match '*path', via: :all, to: redirect('error/404')
  get '*path', to: 'errors#error_404', via: :all
end

app/models/audit.rb
class Audit < ApplicationRecord
  belongs_to :checklist
  has_many :answers, dependent: :destroy

  accepts_nested_attributes_for :answers, reject_if: proc { |attributes| attributes['comment'].blank? }

  # Set up the number of displayed Audit items per page
  self.per_page = 10
end

app/controllers/audits_controller.rb
class AuditsController < ApplicationController
  
  before_action :find_all_checklists, only: [:index]
  before_action :find_checklist!, only: [:new, :create, :show, :update]
  before_action :find_audit!, only:[:show, :destroy, :edit, :create, :update]
  
  # GET /audits
  def index
    @audits = Audit.all
      .order('created_at DESC')
      .paginate(page: params[:page])
  end
  
  # GET checklists/1/audits/1
  def show
  end
  
  # GET checklists/1/audits/new
  def new
    @show_answer_form = true
    @audit = @checklist.audits.create
  end
  
  # GET checklists/1/audits/1/edit
  def edit; end

  # PATCH/PUT checklists/1/audits/1
  def update
    if @audit.update(audit_params)
      flash[:success] = 'Audit was successfully updated.'
      redirect_to checklist_audit_path(@checklist, @audit)
    else
      flash[:success] = 'With updating audit has an error.'
      render :edit
    end
    # redirect_to @audit
  end

  # DELETE checklists/1/audits/1
  def destroy
    if @audit.destroy
      redirect_to audits_path
      flash[:success] = 'Audit was successfully destroyed.' 
    else
      # respond_to :js
      flash[:error] = "Audit has not been deleted! Something went wrong"
      render status: 422
    end
  end
  
  private
    # Find all checklists using to show them in index page 
    def find_all_checklists
      @checklists = Checklist.all
        .paginate(page: params[:page])
    end

    # Find a checklist using it ID
    def find_checklist!
      @checklist = Checklist.find(params[:checklist_id])
    end

      # Only allow a list of trusted parameters through.
    def find_audit!
      @audit = Audit.find(params[:id])
    end

    def audit_params
      params.require(:audit).permit(:checklist_id, answers: [:id, :question_id, :answer, :comment])
    end
end

app/helpers/audits_helper.rb
module AuditsHelper
end

app/views/audits/_form.html.erb
<div class="row answer">
  <div class="col s8 offset-s2">
    <div class="card">
      <div class="card-content answer_comment">
        <%= form_with(model: [@audit.checklist, @audit]) do |form| %>
        <%= form.hidden_field :checklist_id, value: @audit.checklist.id %>

        <div class="field">
            <%= form.fields_for :answers do |f| %>
              <%= render 'answers/edit_form', f: f %>
            <% end %>
        </div>
        <p>
        </p>
          <%= form.submit 'Send Answer', class: 'waves-effect waves-light btn'%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/audits/edit.html.erb
<div class="row">
  <div class="col s8 offset-s2">
    <div class="card">
      <div class="card-content">
        <h5> <%= @audit.checklist.title %></h5>
        <p> <%= @audit.checklist.description %></p>
        <hr />
        <% @audit.checklist.questions.any?  do %>
        <ul class="card-body">
          <span class="card-title">Answer <%= @audit.checklist.count_questions %> Questions:</span>
            <%= render 'form', audit: @audit %>
        </ul>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/audits/index.html.erb
<div class="card material-table">
  <div class="table-header">
    <h5>You're Audits</h5>
    <div class="actions" data-turbolinks="false">
      <!-- Modal Trigger -->
      <a class="waves-effect waves-light btn teal lighten-2 modal-trigger"
         href="#modal1" onclick="$('.modal').modal();">Add new</a>
    </div>
  </div>
  <div id="dttb_wrapper" class="dataTables_wrapper no-footer">
    <table class="responsive nowrap table table-hover dataTable no-footer dtr-inline" data-sort="true" data-source="/posts.json" id="dttb" role="grid" aria-describedby="dttb_info">
      <thead>
        <tr role="row">
          <th colspan="1"></th>
          <th data-data="title" class="sorting center" colspan="3" aria-label="Title: activate to sort column ascending">Checklist Name</th>
          <th data-data="date" class="sorting center" colspan="2" aria-label="Date: activate to sort column ascending">Last Updated</th>
          <th data-data="action" class="sorting center" colspan="2">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @audits.each_with_index do |audit, i| %>
        <tr class=" odd">
          <td valign="top" colspan="1" class="dataTables_empty">
            <b><%= get_row_number(@audits.current_page, i) %><b>
          </td> 
          <td valign="top" colspan="3" class="dataTables_empty">
            <b>
              <%= link_to audit.checklist.title, checklist_audit_path(audit.checklist, audit), title: "Click to show more information" %>
            <b>
          </td>
          <td valign="top" colspan="2" class="dataTables_empty">
            <b>
              <%= time_ago_in_words(audit.updated_at) %>
            <b>
          </td>
          <td valign="top" colspan="1" class="dataTables_empty">
            <%= link_to 'Destroy', checklist_audit_path(audit.checklist, audit), method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
          <td valign="top" colspan="1" class="dataTables_empty">
            <%= link_to 'Edit', edit_checklist_audit_path(audit.checklist, audit) %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="table-footer">
      <div class="dataTables_info" id="dttb_info" role="status" aria-live="polite"><%= get_pages_info(@audits.current_page, @audits.total_pages) %></div>
      <div class="dataTables_paginate paging_full" id="dttb_paginate">
        <%= will_paginate @audits, previous_label: "Older", next_label: "Newer",  class: 'paginate_button first disabled' %>
      </div>
    </div>
  </div>
</div>
<!-- Modal Structure -->
<div id="modal1" class="modal col s4 open offset-s2">
  <div class="modal-content">
    <div class="table-header">
      <h5>Choose one of the checklists:</h5>
    </div>
    <div class="collection with-header">
      <%= render @checklists.published %>
    </div>
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-close waves-effect waves-red btn btn-flat">Cancel</a>
  </div>
</div>

app/views/audits/new.html.erb
<div class="row">
  <div class="col s8 offset-s2">
    <div class="card">
      <div class="card-content" id="audit" data-checklist="<%= @audit.id %>">
        <h5> <%= @checklist.title %></h5>
        <br />
        <p> <%= @checklist.description %></p>
        <br />
        <hr />
        <% @checklist.questions.any?  do %>
        <ul class="card-body">
          <h6 class="center">Answer <%= @checklist.count_questions %> Questions:</h6>
          <%= render @checklist.questions %>
        </ul>
        <% end %>
      </div>
      <div class="card-action">
        <%= link_to 'Create', checklist_audit_path(@checklist, @audit),
            class: 'waves-effect waves-light btn', id: "test_answers" %>
        <%= link_to 'Cancel', checklist_audit_path(@audit.checklist, @audit),
            method: :delete, data: { confirm: 'Are you sure?' },
            class: 'waves-effect waves-light btn red darken-1' %>
      </div>
    </div>
  </div>
</div>
<%= javascript_include_tag "form_validator.js" %>
<%= javascript_include_tag "check_answers.js" %>

app/views/audits/show.html.erb
<div class="row">
  <div class="col s8 offset-s2">
    <div class="card">
      <div class="card-content" id="audit" data-checklist="<%= @audit.id %>">
        <h4 class="center"> Audit &numero;<%= @audit.id %></h4>
        <h5>Title:
          <b><%= @checklist.title %></b>
        </h5>
        <p>Description:
          <b><%= @checklist.description %></b>
        </p>
        <hr>
        <% @checklist.questions.any? do %>
        <table class="responsive nowrap table table-hover dataTable no-footer dtr-inline centered" id="dttb" role="grid" aria-describedby="dttb_info">
          <thead>
            <tr role="row">
              <th data-data="question" class="sorting" colspan=3>Questions</th>
              <th data-data="answer" class="sorting" colspan="2">Answers</th>
            </tr>
          </thead>
          <tbody>
            <% @audit.answers.each_with_index do |answer, i| %>
            <tr class="odd question" data-checklist="<%= answer.id %>" %>
              <td valign="top" class="dataTables_empty"><%= i+1 %></td>
              <td valign="top" class="dataTables_empty"><%= @checklist.questions[i].title %></td>
              <td valign="top" class="dataTables_empty"><%= @checklist.questions[i].description %></td>
              <td valign="top" class="dataTables_empty"><%= answer.answer%></td>
              <td valign="top" class="dataTables_empty"><%= answer.comment%></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <% end %>
      </div>
      <div class="card-action">
        <%= link_to 'Edit',edit_checklist_audit_path(@audit.checklist, @audit), class: 'waves-effect waves-light btn teal lighten-2' %>
        <%= link_to 'All Audits', audits_path, class: 'waves-effect waves-light btn teal lighten-2'%>
      </div>
    </div>
  </div>
</div>