config/routes.rb
Rails.application.routes.draw do
  root 'checklists#index'
  
  resources :checklists do
    resources :questions, only: [:create]
  end

  resources :checklists do
    resources :audits, except: [:index, :create] do
        resources :answers, only: [:create, :edit]
    end
  end
  
  resources :audits, only: [:index]
  devise_for :users
  
  # If no route matches
  # match ":url" => "application#redirect_user", :constraints => { :url => /.*/ }
  # match '*path', via: :all, to: redirect('error/404')
  get '*path', to: 'errors#error_404', via: :all
end

app/models/checklist.rb
class Checklist < ApplicationRecord
  # Checklist can have many questions and when delete a checklist
  # the question that belongs to the specific checklist will be deleted as well. 
  has_many :questions, dependent: :destroy
  has_many :audits, dependent: :destroy
  
  validates :title, presence: true, length: { in: 1..40 }, uniqueness: true
  validates :description, presence: true
  validates :public, default: false

  # Set up the number of displayed Checklist items per page
  self.per_page = 10
  
  # @return [Integer] sum of all questions in the current list
  def count_questions
    questions.count
  end

  scope :published, -> { where(public: true) }

end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  before_action :set_checklist!, only: [:show, :edit, :update, :destroy]

  # GET /checklists
  def index
    @checklists = Checklist.all
      .order('created_at DESC')
      .paginate(page: params[:page])
  end

  # GET /checklists/1
  def show
  end

  # GET /checklists/new
  def new
    @checklist = Checklist.new
  end

  # GET /checklists/1/edit
  def edit
  end

  # POST /checklists
  def create
    @checklist = Checklist.new(checklist_params)
    if @checklist.save
      flash[:success] = 'Checklist was successfully created.'
      redirect_to checklist_path(@checklist)
    else
      flash[:error] = @checklist.errors.full_messages.join("\n")
      render :new, status: 422
    end
  end

  # PATCH/PUT /checklists/1
  def update
    respond_to do |format|
      if @checklist.update(checklist_params)
        format.html { redirect_to @checklist, flash: {success: 'Checklist was successfully updated.' }}
      else
        format.html { render :edit, flash: {error: @checklist.errors, status: :unprocessable_entity }}
      end
    end
  end

  # DELETE /checklists/1
  def destroy
    @checklist.destroy
    respond_to do |format|
      format.html { redirect_to checklists_url }
      flash[:success] = 'Checklist was successfully destroyed.'
    end
  end
  
  def error
  end

  private
    # Find a checklist using it ID
    def set_checklist!
      @checklist = Checklist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def checklist_params
      params.require(:checklist).permit(:title, :description, :public)
    end
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
  
  def get_checkbox_style(public)
    public == true ? 'checked="checked"' : ''
  end

  def get_public_name(public)
    public == true ? 'Published' : 'Unpublished'
  end

end

app/views/checklists/_checklist.html.erb
<%= link_to checklist.title, new_checklist_audit_path(checklist), class: "collection-item black-text" %>

app/views/checklists/_form.html.erb
<%= form_with(model: checklist, local: true) do |form| %>

<div class="field">
  <%= form.label :title, "Title"%>
  <%= form.text_field :title, data: { length:40 }, id: 'input_text', placeholder: "Junior Web Developer Test", required: true %>
</div>

<div class="field">
  <%= form.label :description%>
  <%= form.text_area :description, id: "comment", placeholder: "JavaScript technology stack", required: true %>
</div>

<div class="actions">
  <%= form.submit  class: 'waves-effect waves-light btn teal lighten-2'%>
  <%= link_to 'Cancel', checklists_path, class: 'waves-effect waves-light btn red darken-1' %>
</div>
<% end %>

app/views/checklists/edit.html.erb
<div class="row">
  <div class="col s8 offset-s2">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Editing Checklist</span>
        <%= render 'form', checklist: @checklist %>
      </div>
    </div>
  </div>
</div>
<%= javascript_include_tag "form_validator.js" %>

app/views/checklists/index.html.erb
<div class="card material-table">
  <div class="table-header">
    <h5>You're Checklists</h5>
    <div class="actions">
      <a class="waves-effect btn teal lighten-2" href="<%= new_checklist_path %>">Add new</a>
    </div>
  </div>
  <div id="dttb_wrapper" class="dataTables_wrapper no-footer">
    <table class="responsive nowrap table table-hover dataTable no-footer dtr-inline" data-sort="true" id="dttb" role="grid">
      <thead>
        <tr role="row">
          <th></th>
          <th data-data="title" class="sorting center" colspan="5" aria-label="Title: activate to sort column ascending">Title</th>
          <th data-data="body" class="sorting center" colspan="2" aria-label="Body: activate to sort column ascending" aria-sort="descending">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @checklists.each_with_index do |checklist, i| %>
          <tr class="odd">
            <td valign="top" colspan="1" class="dataTables_empty">
              <b><%= get_row_number(@checklists.current_page, i) %><b>
            </td> 
            <td valign="top" colspan="5" class="dataTables_empty"><b><%= link_to checklist.title, checklist, title: "Click to show more information" %><b></td>
            <td valign="top" colspan="2" class="dataTables_empty"><%= link_to 'Destroy', checklist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="table-footer">
      <div class="dataTables_info" id="dttb_info" role="status" aria-live="polite"><%= get_pages_info(@checklists.current_page, @checklists.total_pages) %></div>
      <div class="dataTables_paginate paging_full" id="dttb_paginate">
        <%= will_paginate @checklists, previous_label: "Older", next_label: "Newer",  class: 'paginate_button first disabled' %>
      </div>

    </div>
  </div>
</div>

app/views/checklists/new.html.erb
<div class="row">
  <div class="col s8 offset-s2">
    <div class="card">
      <div class="card-content">
        <span class="card-title">New Checklist</span>
        <%= render 'form', checklist: @checklist %>
      </div>
    </div>
  </div>
</div>
<%= javascript_include_tag "form_validator.js" %>

app/views/checklists/show.html.erb
<div class="row">
  <div class="col s8 offset-s2">
    <div class="card">
      <div class="card-content" id="checklist" data-checklist="<%= @checklist.id %>">
        <h5>Title:
          <b><%= @checklist.title %></b>
        </h5>
        <br/>
        <p>Description:
          <b><%= @checklist.description %></b>
        </p>
        <br/>
        <hr />
        <% @checklist.questions.any?  do %>
        <ul class="card-body">
          <span class="card-title center"><%= get_questions_title(@checklist.count_questions) %></span>
          <%= render @checklist.questions %>
        </ul>
        <% end %>
      </div>
      <div class="card-action">
        <%= link_to 'Edit', edit_checklist_path(@checklist), class: 'waves-effect waves-light btn teal lighten-2' %>
        <%= link_to 'Delete', @checklist, method: :delete,
            data: { confirm: 'Are you sure?' },
            class: 'waves-effect waves-light btn red darken-1' %>
        <%= link_to 'All Checklists', checklists_path, class: 'waves-effect waves-light btn teal lighten-2'%>
        <label>
          <input type="checkbox" name="checkbox" class="filled-in" <%= get_checkbox_style(@checklist.public) %> />
          <span><%= get_public_name(@checklist.public) %></span>
        </label>
      </div>
    </div>
  </div>
</div>
<%= render "questions/form" %>
<%= javascript_include_tag "form_validator.js" %>
<%= javascript_include_tag "publish_checklist.js" %>