config/routes.rb
Rails.application.routes.draw do
  root 'checklists#index'
  
  resources :checklists do
    resources :questions, only: [:create]
  end

  resources :checklists do
    resources :audits, except: [:index, :create] do
        resources :answers, only: [:create, :edit]
    end
  end
  
  resources :audits, only: [:index]
  devise_for :users
  
  # If no route matches
  # match ":url" => "application#redirect_user", :constraints => { :url => /.*/ }
  # match '*path', via: :all, to: redirect('error/404')
  get '*path', to: 'errors#error_404', via: :all
end

app/views/layouts/_footer.html.erb
  <footer class="page-footer ligt-gree">
    <div class="footer-copyright light-green darken-1">
      <div class="container">
        © Copyright <%= Date.today.year %>
      <div class="right">
        Source code available on
        <a href='https://github.com/Synkevych/nested_rails_forms' target='_blank' rel='noopener noreferrer'>
            GitHub
        </a>
      </div>
      </div>
    </div>
  </footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="light-green darken-1 nav-wrapper" role="navigation">
    <div class="nav-wrapper container">
      <a href="<%= root_path %>" class="brand-logo pl-2">RubyForms</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if user_signed_in? %>
          <li><a href="<%= root_path %>">Checklists</a></li>
          <li><a href="<%= audits_path %>">Audits</a></li>
          <li> <%= link_to 'Edit profile', edit_user_registration_path %></li>
          <li> <%= link_to "Logout " + current_user.email, destroy_user_session_path, method: :delete, title: "Click to logout" %></li>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %> |
          <%= link_to "Login", new_user_session_path %>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>ProjIDHr014</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application' %>
</head>

<body>
  <%= render 'layouts/header' %>
  <div class="flashes">
    <%= render 'shared/error' %>
  </div>
  <main>
    <div class="container">
      <div class="row">
        <div class="col s12">
          <%= yield %>
        </div>
      </div>
    </div>
  </main>
  <%= render 'layouts/footer' %>

</body>

</html>